### ISSUE TITLE
Statamic 4 Issue

### ISSUE THREAD

**Issue by rhoraczek** [nineteen-2/statamic-instagram-basic-display-api#16]
Hi there,
after a new Statamic 4.0 installation I get the following error in the terminal when installing your Instagram addon. Is this message exclusively related to the Statamic version or is there something else I need to consider before installing the addon?

Cheers, Rudolf

```./composer.json has been updated
Running composer update nineteensquared/instagram
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   UnexpectedValueException 

  Invalid route action: [InstagramLogoutController].

  at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
     88▕      */
     89▕     protected static function makeInvokable($action)
     90▕     {
     91▕         if (! method_exists($action, '__invoke')) {
  ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     93▕         }
     94▕ 
     95▕         return $action.'@__invoke';
     96▕     }

  i   `InstagramLogoutController` is not invokable: The controller class `InstagramLogoutController` is not invokable. Did you forget to add the `__invoke` method or is the controller's method missing in your routes file? 

      +41 vendor frames 
  42  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1```

**Comment by adevade** [comment]
I think this is caused by the default route namespace being removed. [I fixed it in a fork](https://github.com/adevade/statamic-instagram-basic-display-api/commit/b3ff06a4d37d2e775a94d67595f3bf0571dd3cbd), temporarily, while waiting for an update.

Here's the related point in the upgrade guide: https://statamic.dev/upgrade-guide/3-4-to-4-0#route-namespaces-have-been-removed

**Comment by rhoraczek** [comment]
Thans,
I've tried again with "composer require nineteensquared/instagram", but unfortunately with the same result/error.

**Comment by adevade** [comment]
@rhoraczek If you just want to get it working, you can add this to your `composer.json`:

```diff
"require": {
    ...
-    "nineteensquared/instagram": "^1.1",
+    "nineteensquared/instagram": "dev-master",
    ...
},

...

+"repositories": [
+    {
+        "type": "git",
+        "url": "https://github.com/adevade/statamic-instagram-basic-display-api"
+    }
+]
```

This will make Composer download the `master` branch from my fork instead. [Here's what I updated](https://github.com/adevade/statamic-instagram-basic-display-api/commit/b3ff06a4d37d2e775a94d67595f3bf0571dd3cbd).

**Disclaimer though**: I *don't* plan on supporting a fork. This is only a temporary fix until the original package is updated or another one replaces it. I've only tested it locally, so no guarantee that it works perfectly. 

I may delete my fork at any time, just so you are aware. If you want to, you could make your own fork, to be sure. Just update the url in the repositories array.

**Comment by rhoraczek** [comment]
Great! It works, locally and on the live website.
I will leave this as an interim solution until there is news for the package.
Thanks for your effort @adevade
