### ISSUE TITLE
Statamic 4 support

### ISSUE THREAD

**Issue by adevade** [nineteen-2/statamic-instagram-basic-display-api#17]
Hey! Thanks for your addon! It's been working great for us for over a year now.

Are there any plans for supporting the newly released Statamic 4? Right now an error is thrown when installing on Statamic 4, due to how they handle controllers differently. 

More info: https://statamic.dev/upgrade-guide/3-4-to-4-0#route-namespaces-have-been-removed

**Comment by mscruse** [comment]
What's the current status of this having 4 support?

**Comment by lbeauvisage** [comment]
Sorry I have no plan to update for Statamic 4

**Comment by adevade** [comment]
@lbeauvisage Would you accept a PR that updates to support v4, and release that as a new major version?

**Comment by lbeauvisage** [comment]
@adevade I've just merge a PR from @atopping that should fix the problem for Statamic V4
