### ISSUE TITLE
Instagram Basic Display API deprected on December 4 2024

### ISSUE THREAD

**Issue by wm-simon** [nineteen-2/statamic-instagram-basic-display-api#19]
META:
Starting December 4, 2024, all requests to the Instagram Basic Display API will return an error message. We recommend that you migrate your app to the [Instagram API](https://developers.facebook.com/docs/instagram-platform) to avoid any disruption to your services.

More information here:
https://developers.facebook.com/blog/post/2024/09/04/update-on-instagram-basic-display-api/

Will this addon still work after December 4, 2024? If not, are there any plans to update it?

Thanks for your feedback!

**Comment by lbeauvisage** [comment]
I no longer maintain this addon, there are no plans to update it.
It is therefore possible that it will no longer work at all on December 4th.
