### ISSUE TITLE
Feed broken

### ISSUE THREAD

**Issue by robdekort** [nineteen-2/statamic-instagram-basic-display-api#5]
Hi, my feed broke. The customer removed the app from instagram, but now I can't restore the connection. On the config page in the CP I get:

ErrorException
Undefined property: stdClass::$username (View: /Users/robdekort/Sites/codegorilla/vendor/nineteensquared/instagram/resources/views/index.blade.php)

**Comment by samshupac** [comment]
I have exactly the same issue, did you get anywhere with this?
Any help appreciated.

**Comment by robdekort** [comment]
I'm so so sorry, I did, somehow, I can't remember how.

**Comment by lbeauvisage** [comment]
thank you for your feedback @samshupac @robdekort 
I publish a [new release](https://github.com/nineteen-2/statamic-instagram-basic-display-api/releases/tag/1.1.0)
to catch the error and be able to logout if the app is removed from instagram (and login again after)

let me know if all is OK

**Comment by robdekort** [comment]
Nice! Thank you. Will let you know if I run into issues again.
